# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdowgems: [jekyll-paginate]

# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# Gems
gems:
  - jekyll-paginate


