# Setup
title:       欢迎光临 
tagline:      ""
baseurl:      ""
paginate:     10
paginate_path: "/blog/page:num/"

# About/contact
author:
  name:       夏目任曦
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-slate
